GLOBAL:
  era: Run3_2022EE
  luminosity: 26671.7 # pb-1
  fs_nanoAOD:
  - 'T2_CH_CERN:/store/group/phys_higgs/HLepRare/skim_2024_v1/Run3_2022EE'
  nano_version: v14
  crossSectionsFile : config/crossSections13TeV.yaml
  use_stitching: false

DYto2L_M-50_madgraphMLM:
  sampleType: DY
  crossSection: DY_NNLO
  crossSectionStitch: DY_NLO
  isReference: true
  generator: madgraph
############## Data ##############
EGamma_Run2022E:
  sampleType: data
EGamma_Run2022F:
  sampleType: data
EGamma_Run2022G:
  sampleType: data
Muon_Run2022E:
  sampleType: data
Muon_Run2022F:
  sampleType: data
Muon_Run2022G:
  sampleType: data
MuonEG_Run2022E:
  sampleType: data
MuonEG_Run2022F:
  sampleType: data
MuonEG_Run2022G:
  sampleType: data
Tau_Run2022E:
  sampleType: data
Tau_Run2022F:
  sampleType: data
Tau_Run2022G:
  sampleType: data
JetMET_Run2022E:
  sampleType: data
JetMET_Run2022F:
  sampleType: data
JetMET_Run2022G:
  sampleType: data
