
- name: QCD
  title: QCD
  color: kPink+1
- name: DY
  title: "DY #rightarrow ll + jets"
  color: kAzure+10
- name: TT
  title: t#bar{t}
  color: kGreen-3
- name: W
  title: "W #rightarrow l#nu + jets"
  color: kYellow-7
#- name: HHnonRes
  #title: "HH SM"
  #color: kPink+1
- name: EWK
  title: "EWK"
  color: kViolet-4
- name: ST
  title: "ST"
  color: kTeal
#- name: ttH
#  title: "ttH"
#  color: kOrange+1
#- name: TTX
#  title: "TTX"
#  color: kRed+3
- name: VV
  title: "VV"
  color: kBlue+3
#- name: VVV
#  title: "VVV"
#  color: kPink+6
- name: GluGluToBulkGraviton_1250
  title: "GGBG-1250"
  type: signal
  color: kGreen
  #scale: 0.05
- name: GluGluToRadion_1250
  title: "GGR-1250"
  type: signal
  color: kCyan
- name: GluGluToRadion_700
  title: "GGR-700"
  type: signal
  color: kBlue
- name: GluGluToRadion_450
  title: "GGR-450"
  type: signal
  color: kViolet
- name: Other
  title: "Other"
  color: kRed-4
- name: data
  title: "data obs"
  type: data