GLOBAL:
  era: Run3_2023
  luminosity: 7980.4 # pb-1
  fs_nanoAOD:
  - 'T2_CH_CERN:/store/group/phys_higgs/HLepRare/skim_2024_v1/Run3_2023'
  nano_version: v14
  crossSectionsFile : config/crossSections13p6TeV.yaml
  triggerFile: config/Run3_2023/triggers.yaml
  use_stitching: false
  met_type: PFMET

TTto2L2Nu:
  crossSection: TTto2L2Nu
  generator: powheg
  miniAOD: Missing
  sampleType: TT
