cmsswPython: RunKit/nanoProdWrapper.py
params:
  customise: Framework/NanoProd/customiseNano.customise
  skimCfg: skim.yaml
  maxEvents: -1
splitting: FileBased
unitsPerJob: 4
scriptExe: RunKit/nanoProdCrabJob.sh
outputFiles:
  - nano.root
filesToTransfer:
  - RunKit/nanoProdCrabJob.sh
  - RunKit/nanoProdCrabJob.py
  - RunKit/skim_tree.py
  - RunKit/sh_tools.py
  - config/skim.yaml
  - NanoProd/skimNano.py

# Update destination site and paths before launching a production
# site: T3_CH_CERNBOX
#crabOutput: /store/user/kandroso/bbtt-prod
#localCrabOutput: /eos/home-k/kandroso/bbtt-prod
#finalOutput: /eos/home-p/kandroso/bbtt/nanoV10

maxMemory: 2500
numCores: 1
inputDBS: global
allowNonValid: False
dryrun: False
maxResubmitCount: 2
maxRecoveryCount: 2
updateInterval: 60 # minutes
postProcessing:
  lawTask: CrabNanoProdTaskPostProcess
  workflow: htcondor
  bootstrap: bootstrap.sh
postProcessingDoneFlag: post_processing_done.txt
#  requirements: ( (OpSysAndVer =?= "CentOS7") || (OpSysAndVer =?= "CentOS8") )
targetOutputFileSize: 2048 # MiB
renewKerberosTicket: True
