unc_source: weight_central_total
  expression : weight_TauID_Central * weight_total
unc_source: TauID_stat1_DM0
  expression: weight_TauID_stat1_dm0{scale}_rel * weight_central_total
unc_source: TauID_stat1_DM10
  expression: weight_TauID_stat1_dm10{scale}_rel * weight_central_total
unc_source: TauID_stat1_DM1
  expression: weight_TauID_stat1_dm1{scale}_rel * weight_central_total
unc_source: TauID_stat1_DM11
  expression: weight_TauID_stat1_dm11{scale}_rel * weight_central_total
unc_source: TauID_stat2_DM0
  expression: weight_TauID_stat2_dm0{scale}_rel * weight_central_total
unc_source: TauID_stat2_DM10
  expression: weight_TauID_stat2_dm10{scale}_rel * weight_central_total
unc_source: TauID_stat2_DM1
  expression: weight_TauID_stat2_dm1{scale}_rel * weight_central_total
unc_source: TauID_stat2_DM11
  expression: weight_TauID_stat2_dm11{scale}_rel * weight_central_total
unc_source: TauID_syst_alleras
  expression: weight_TauID_syst_alleras{scale}_rel * weight_central_total
unc_source: TauID_syst_year
  expression: weight_TauID_syst_year{scale}_rel * weight_central_total
unc_source: TauID_syst_year_DM0
  expression: weight_TauID_syst_year_dm0{scale}_rel * weight_central_total
unc_source: TauID_syst_year_DM1
  expression: weight_TauID_syst_year_dm1{scale}_rel * weight_central_total
unc_source: TauID_syst_year_DM10
  expression: weight_TauID_syst_year_dm10{scale}_rel * weight_central_total
unc_source: TauID_syst_year_DM11
  expression: weight_TauID_syst_year_dm11{scale}_rel * weight_central_total
unc_source: TauID_genuineMuon_etaLt0p4Up
  expression: weight_TauID_TauID_genuineMuon_etaLt0p4Up{scale}_rel * weight_central_total
unc_source: TauID_genuineMuon_eta0p4to0p8
  expression: weight_TauID_TauID_genuineMuon_eta0p4to0p8{scale}_rel * weight_central_total
unc_source: TauID_genuineMuon_eta0p8to1p2
  expression: weight_TauID_TauID_genuineMuon_eta0p8to1p2{scale}_rel * weight_central_total
unc_source: TauID_genuineMuon_eta1p2to1p7
  expression: weight_TauID_TauID_genuineMuon_eta1p2to1p7{scale}_rel * weight_central_total
unc_source: TauID_genuineMuon_etaGt1p7
  expression: weight_TauID_TauID_genuineMuon_etaGt1p7{scale}_rel * weight_central_total
unc_source: TauID_genuineElectron_barrel
  expression: weight_TauID_TauID_genuineElectron_barrel{scale}_rel * weight_central_total
unc_source: TauID_genuineElectron_endcaps
  expression: weight_TauID_TauID_genuineElectron_endcaps{scale}_rel * weight_central_total
unc_source: TauID_total
  expression: weight_TauID_total{scale}_rel * weight_central_total
unc_source: bTagSF_Loose_btagSFbc_correlated
  expression: weight_bTagSF_Loose_btagSFbc_correlated{scale}_rel * weight_bTagSF_Loose_Central
unc_source: bTagSF_Loose_btagSFbc_uncorrelated
  expression: weight_bTagSF_Loose_btagSFbc_uncorrelated{scale}_rel * weight_bTagSF_Loose_Central
unc_source: bTagSF_Loose_btagSFlight_correlated
  expression: weight_bTagSF_Loose_btagSFlight_correlated{scale}_rel * weight_bTagSF_Loose_Central
unc_source: bTagSF_Loose_btagSFlight_uncorrelated
  expression: weight_bTagSF_Loose_btagSFlight_uncorrelated{scale}_rel * weight_bTagSF_Loose_Central
unc_source: bTagSF_Medium_btagSFbc_correlated
  expression: weight_bTagSF_Medium_btagSFbc_correlated{scale}_rel * weight_bTagSF_Medium_Central
unc_source: bTagSF_Medium_btagSFbc_uncorrelated
  expression: weight_bTagSF_Medium_btagSFbc_uncorrelated{scale}_rel * weight_bTagSF_Medium_Central
unc_source: bTagSF_Medium_btagSFlight_correlated
  expression: weight_bTagSF_Medium_btagSFlight_correlated{scale}_rel * weight_bTagSF_Medium_Central
unc_source: bTagSF_Medium_btagSFlight_uncorrelated
  expression: weight_bTagSF_Medium_btagSFlight_uncorrelated{scale}_rel * weight_bTagSF_Medium_Central
unc_source: bTagSF_Tight_btagSFbc_correlated
  expression: weight_bTagSF_Tight_btagSFbc_correlated{scale}_rel * weight_bTagSF_Tight_Central
unc_source: bTagSF_Tight_btagSFbc_uncorrelated
  expression: weight_bTagSF_Tight_btagSFbc_uncorrelated{scale}_rel * weight_bTagSF_Tight_Central
unc_source: bTagSF_Tight_btagSFlight_correlated
  expression: weight_bTagSF_Tight_btagSFlight_correlated{scale}_rel * weight_bTagSF_Tight_Central
unc_source: bTagSF_Tight_btagSFlight_uncorrelated
  expression: weight_bTagSF_Tight_btagSFlight_uncorrelated{scale}_rel * weight_bTagSF_Tight_Central
unc_source: PUJetID_b1
  expression: weight_Jet_PUJetID_eff{scale}_rel_b1 * weight_Jet_PUJetID_Central_b1
unc_source: PUJetID_b2
  expression: weight_Jet_PUJetID_eff{scale}_rel_b2 * weight_Jet_PUJetID_Central_b2
unc_source: PileUp
   expression: weight_pu{scale}_rel * weight_total
unc_source: EleID_tau1
  expression: weight_tau1_EleidSF_{scale}_rel * weight_tau1_EleidSF_Central
unc_source: EleID_tau2
  expression: weight_tau2_EleidSF_{scale}_rel * weight_tau2_EleidSF_Central
unc_source: MuID_tau1_TightRelIso
  expression: weight_tau1_MuidSF_TightRelIso{scale}_rel * weight_tau1_MuidSF_Central
unc_source: MuID_tau2_TightRelIso
  expression: weight_tau1_MuidSF_TightRelIso{scale}_rel * weight_tau2_MuidSF_Central
unc_source: MuID_tau1_TightID
  expression: weight_tau1_MuidSF_TightID{scale}_rel * weight_tau1_MuidSF_Central
unc_source: MuID_tau2_TightID
  expression: weight_tau1_MuidSF_TightID{scale}_rel * weight_tau2_MuidSF_Central
unc_source: TrigSF_diTau_DM0_tau1
  expression: weight_tau1_TrgSF_ditau_DM0{scale}_rel*weight_tau1_TrgSF_ditau_Central
unc_source: TrigSF_diTau_DM1_tau1
  expression: weight_tau1_TrgSF_ditau_DM1{scale}_rel*weight_tau1_TrgSF_ditau_Central
unc_source: TrigSF_diTau_3Prong_tau1
  expression: weight_tau1_TrgSF_ditau_3Prong{scale}_rel*weight_tau1_TrgSF_ditau_Central
unc_source: TrigSF_diTau_DM0_tau2
  expression: weight_tau2_TrgSF_ditau_DM0{scale}_rel*weight_tau2_TrgSF_ditau_Central
unc_source: TrigSF_diTau_DM1_tau2
  expression: weight_tau2_TrgSF_ditau_DM1{scale}_rel*weight_tau2_TrgSF_ditau_Central
unc_source: TrigSF_diTau_3Prong_tau2
  expression: weight_tau2_TrgSF_ditau_3Prong{scale}_rel*weight_tau2_TrgSF_ditau_Central
unc_source: TrigSF_singleEle_tau1
  expression: weight_tau1_TrgSF_singleEle{scale}_rel*weight_tau1_TrgSF_singleEle_Central
unc_source: TrigSF_singleEle_tau2
  expression: weight_tau2_TrgSF_singleEle{scale}_rel*weight_tau2_TrgSF_singleEle_Central
unc_source: TrigSF_singleMu_tau1
  expression: weight_tau1_TrgSF_singleMu{scale}_rel*weight_tau1_TrgSF_singleMu_Central
unc_source: TrigSF_singleMu_tau2
  expression: weight_tau2_TrgSF_singleMu{scale}_rel*weight_tau2_TrgSF_singleMu_Central